export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const ACCESS_KEY = 'sXHCp2opUUgVl4NBR9eeuijO4VJjqYQCTjsfKIX4mvs';
export const SECRET_KEY = '-TRW9mqWITUDjC9gYct2Ytkf5vdN9S8Rath4NyI-Dy8';
export const REDIRECT_URI = 'https://photo-stream-wee-owl.vercel.app/';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';
